version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_const"
    ports:
      - 80:80
    depends_on:
      - django_app

  django_app:
    image: django_app
    build:
      context: ./django_app
    container_name: "django_const"
    ports: 
      - 8001:8001      
    command: gunicorn core.wsgu --bind 0.0.0.0:8001
    env_file:
      - "./env"
    depends_on:
      - db

  db:
    image: mysql
    container_name: "db_const"
    volumes:
      - ./data/mysql/db:/var/lib/mysql